Features/tvos compatibility
rvi/ONVIFCamera pull request #3
Opened 2018-06-08 10:43 UTC by mohamed-arradi

TV OS Support 
 
Due to an idea realized during the ONVIFCamera Challenge I was unable to import ONVIFCamera SDK on the TV OS App. 
 
Now it is possible ! 

## Description

So in order to make it happening there was an issue about the SOAP Engine which was compiled only for iOS. Then you cannot have the same SOAPEngine inside the pod... 

So I decided to create an another pod spec for the Apple TV which use the same base code but just has a different header file regarding libraries.

## Motivation and Context

It fixes an issue I had during the ONVIFChallenge, which was I could not use ONVIF SDK on an TV OS Target even if on the main pod spec it was specified. 

## How Has This Been Tested?

Manually

## Screenshots:

![simulator screen shot - apple tv 4k - 2018-06-08 at 14 42 14](https://user-images.githubusercontent.com/3295294/41154124-2b3f1556-6b2a-11e8-9b63-59c6faf88f34.png)

2018-06-28 12:51 UTC, rvi requested changes

2018-06-28 12:51 UTC, rvi commented on Example/ONVIFCamera/FormViewController.swift
> -import ONVIFCamera
Doesn't compile anymore on iOS...

2018-06-28 12:51 UTC, rvi commented
Hi Mohamed,

Sorry for the silence, I was quite busy these days, thanks a lot for this great PR!! You rock!
I'm adding a few comments in the code.

- There is some new files in the filesystem that looks like a Ruby code, `Pod::Spec.new` and `do`.
Can you remove them?
- Also you modify the copyright in some files, I think it was automatic, can you revert those changes?
- Some warnings have been added when we run pod install in the project
- The test project doesn't compile on iOS anymore because we're importing ONVIFCameraTVOS.
- Lastly I'm not a big fan of having 2 different pods and it seems it should be doable with a subspec, like [this example](https://github.com/OneDrive/onedrive-sdk-ios/blob/master/OneDriveSDK.podspec)

2018-07-29 05:45 UTC, mohamed-arradi commented
@rvi Hello Remy. 

Sorry for the late reply too,

So just to reply to some of your comments. 

**- Copyright** : Yes this is my Xcode I will change them manually to the one which are in the ONVIF projects. Because it is just text I did not make really attention to it.

**- Differents Pods:** So I looked across the whole web just to see how we can do it, and I get to the same thing as you. Indeed we can have different OS Targets in one pod spec.

 However here the issue is not to make the ONVIFCamera Pod shared across TVOs and iOS. The main issue I have been faced is the dependencies... For instance ONVIFCamera iOS use SoapEngine and for TV OS we need to use SoapEngineTV as per below : 

```
s.vendored_frameworks = 'ONVIFCamera/SOAPEngine/SOAPEngineTV.framework'
s.public_header_files = 'ONVIFCamera/SOAPEngine/SOAPEngineTV.framework/Headers/*.h'
```

Their is no way in a pod spec to do a "If/else" configuration . Hence why the two pod which are the same but have different dependencies.  So if you know how to do it I will be pleased to remove this "useless" second pod. 

- Test Project: Will look into it, as far as I remember their was no issues but will check again.

2023-01-18 21:36 UTC, closed without merging